### ISSUE TITLE
Compatible with other emulators besides Bluestacks?

### ISSUE THREAD

**Issue by Nathan-Duong** [purpxd/E7AutoShop#1]
Does this program work with other Emulators besides Bluestacks like MuMu?

**Comment by purpxd** [comment]
> 

I've tested it with Bluestacks and also LDplayer. I haven't tried with MuMu but if there is an Android Debug Bridge setting in the advanced settings then I don't see why it wouldn't work for MuMu.

**Comment by Nathan-Duong** [comment]
Thanks.
