### ISSUE TITLE
Crash after first refresh

### ISSUE THREAD

**Issue by Urinini** [purpxd/E7AutoShop#11]
The app seems to crash after the first refresh happens. I tried reinstalling bluestacks, installing LDPlayer, replacing the adb.exe and 2dlls with platform-tools ones. Here is the error log:

ERROR:root:cannot identify image file <_io.BytesIO object at 0x0000024A8264EFC0>
Traceback (most recent call last):
  File "scripts\shop.py", line 272, in main
    screenshot = self.screen()
                 ^^^^^^^^^^^^^
  File "scripts\shop.py", line 115, in screen
    screenshot = Image.open(BytesIO(img_bytes))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PIL\Image.py", line 3298, in open
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x0000024A8264EFC0>
ERROR:root:cannot identify image file <_io.BytesIO object at 0x0000013B4E7E9D50>
Traceback (most recent call last):
  File "scripts\shop.py", line 272, in main
    screenshot = self.screen()
                 ^^^^^^^^^^^^^
  File "scripts\shop.py", line 115, in screen
    screenshot = Image.open(BytesIO(img_bytes))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PIL\Image.py", line 3298, in open
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x0000013B4E7E9D50>

Here's a video of what happens in game (not sure if this is the way it's supposed to work since it crashes), basically it refreshes and does a few hectic clicks and crashes (same thing happens on both emulators): https://imgur.com/a/rLADjVn

**Comment by purpxd** [comment]
> The app seems to crash after the first refresh happens. I tried reinstalling bluestacks, installing LDPlayer, replacing the adb.exe and 2dlls with platform-tools ones. Here is the error log:
> 
> ERROR:root:cannot identify image file <_io.BytesIO object at 0x0000024A8264EFC0> Traceback (most recent call last): File "scripts\shop.py", line 272, in main screenshot = self.screen() ^^^^^^^^^^^^^ File "scripts\shop.py", line 115, in screen screenshot = Image.open(BytesIO(img_bytes)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "PIL\Image.py", line 3298, in open PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x0000024A8264EFC0> ERROR:root:cannot identify image file <_io.BytesIO object at 0x0000013B4E7E9D50> Traceback (most recent call last): File "scripts\shop.py", line 272, in main screenshot = self.screen() ^^^^^^^^^^^^^ File "scripts\shop.py", line 115, in screen screenshot = Image.open(BytesIO(img_bytes)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "PIL\Image.py", line 3298, in open PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x0000013B4E7E9D50>
> 
> Here's a video of what happens in game (not sure if this is the way it's supposed to work since it crashes), basically it refreshes and does a few hectic clicks and crashes (same thing happens on both emulators): https://imgur.com/a/rLADjVn

Hello,
Where did you install the program in? You will run into a permission issue if you installed it in your systems path (Program Files x86) which is the default for the installer. Try installing it somewhere in your users path such as documents or anywhere on a external drive and it should work just fine.

**Comment by Urinini** [comment]
It seems to be working now! Also, while redownloading the installer, I've noticed it's mentioned in the releases section, but I didn't see it the first time around since I clicked on the direct download link in the readme (might be worth adding it there too). Thanks for the help!
