### ISSUE TITLE
Crashing shortly after pressing start

### ISSUE THREAD

**Issue by CamdenBigelow** [purpxd/E7AutoShop#13]
Error.log file is as follows: 
```
ERROR:root:cannot identify image file <_io.BytesIO object at 0x000001E513B56660>
Traceback (most recent call last):
  File "scripts\shop.py", line 272, in main
    screenshot = self.screen()
                 ^^^^^^^^^^^^^
  File "scripts\shop.py", line 115, in screen
    screenshot = Image.open(BytesIO(img_bytes))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PIL\Image.py", line 3298, in open
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000001E513B56660>
```

**Comment by purpxd** [comment]
> 
> 
> Error.log file is as follows: 
> 
> ```
> 
> ERROR:root:cannot identify image file <_io.BytesIO object at 0x000001E513B56660>
> 
> Traceback (most recent call last):
> 
>   File "scripts\shop.py", line 272, in main
> 
>     screenshot = self.screen()
> 
>                  ^^^^^^^^^^^^^
> 
>   File "scripts\shop.py", line 115, in screen
> 
>     screenshot = Image.open(BytesIO(img_bytes))
> 
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "PIL\Image.py", line 3298, in open
> 
> PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000001E513B56660>
> 
> ```
> 
> 

Where did you install the program?

**Comment by CamdenBigelow** [comment]
> > Error.log file is as follows:
> > ```
> > 
> > ERROR:root:cannot identify image file <_io.BytesIO object at 0x000001E513B56660>
> > 
> > Traceback (most recent call last):
> > 
> >   File "scripts\shop.py", line 272, in main
> > 
> >     screenshot = self.screen()
> > 
> >                  ^^^^^^^^^^^^^
> > 
> >   File "scripts\shop.py", line 115, in screen
> > 
> >     screenshot = Image.open(BytesIO(img_bytes))
> > 
> >                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > 
> >   File "PIL\Image.py", line 3298, in open
> > 
> > PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000001E513B56660>
> > ```
> 
> Where did you install the program?

It is installed within a folder on my Desktop.

**Comment by purpxd** [comment]
> > > Error.log file is as follows:
> 
> > > ```
> 
> > > 
> 
> > > ERROR:root:cannot identify image file <_io.BytesIO object at 0x000001E513B56660>
> 
> > > 
> 
> > > Traceback (most recent call last):
> 
> > > 
> 
> > >   File "scripts\shop.py", line 272, in main
> 
> > > 
> 
> > >     screenshot = self.screen()
> 
> > > 
> 
> > >                  ^^^^^^^^^^^^^
> 
> > > 
> 
> > >   File "scripts\shop.py", line 115, in screen
> 
> > > 
> 
> > >     screenshot = Image.open(BytesIO(img_bytes))
> 
> > > 
> 
> > >                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> > > 
> 
> > >   File "PIL\Image.py", line 3298, in open
> 
> > > 
> 
> > > PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000001E513B56660>
> 
> > > ```
> 
> > 
> 
> > Where did you install the program?
> 
> 
> 
> It is installed within a folder on my Desktop. 

Try a few things:
1. Enable adb in emu settings if not
2. Run as admin
3. Restart your emulator completely 
4. Try installing or running in different place such as /user/Documents, /user/Downloads

**Comment by CamdenBigelow** [comment]
I will try a combination of those steps, I didn't have any issues until the most recent update to E7 and so wondered if they might be related.

**Comment by purpxd** [comment]
> I will try a combination of those steps, I didn't have any issues until the most recent update to E7 and so wondered if they might be related. 

Ok let me know if it worked. E7 updating wouldn't affect the program as the program only interacts with the emulator, not the game itself.

**Comment by CamdenBigelow** [comment]
No luck unfortunately. I should note perhaps that I had been using a much older version of autoshop for some time and it suddenly started to crash so I went to install the current version and the issue persisted. Probably an issue on my end tbh.

**Comment by nammerduong** [comment]
I also crash shortly after pressing start. I have the adb on and the right resolution on bluestacks. This doesn't work at all for me.

**Comment by TrickyVicky4** [comment]
I am also getting the error.

ERROR:root:cannot identify image file <_io.BytesIO object at 0x000001DCE0E24090>
Traceback (most recent call last):
  File "scripts\shop.py", line 272, in main
    screenshot = self.screen()
                 ^^^^^^^^^^^^^
  File "scripts\shop.py", line 115, in screen
    screenshot = Image.open(BytesIO(img_bytes))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PIL\Image.py", line 3298, in open
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000001DCE0E24090>

**Comment by purpxd** [comment]
> I am also getting the error.
> 
> ERROR:root:cannot identify image file <_io.BytesIO object at 0x000001DCE0E24090> Traceback (most recent call last): File "scripts\shop.py", line 272, in main screenshot = self.screen() ^^^^^^^^^^^^^ File "scripts\shop.py", line 115, in screen screenshot = Image.open(BytesIO(img_bytes)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "PIL\Image.py", line 3298, in open PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000001DCE0E24090>

Where did you install the app?

**Comment by TrickyVicky4** [comment]
At first, /documents then later /downloads. 

EDIT: I swapped to C:\E7AutoShop and now it works. Love the program and will also try the new auto hunt. Ill comment if anything went wrong for that. <3

**Comment by purpxd** [comment]
> At first, /documents then later /downloads.
> 
> EDIT: I swapped to C:\E7AutoShop and now it works. Love the program and will also try the new auto hunt. Ill comment if anything went wrong for that. <3

Awesome! glad you like it! Yeah it usually comes down to some strange permissions thing in certain directories.
