### ISSUE TITLE
Question about auto hunt

### ISSUE THREAD

**Issue by TrickyVicky4** [purpxd/E7AutoShop#14]
I tried the auto-hunt mechanic, but it does nothing, so I'm pretty sure I'm doing it wrong. What i did was i went into repeat battle, exited to lobby with background battling, and then had the UI visible.

**Comment by purpxd** [comment]
> I tried the auto-hunt mechanic, but it does nothing, so I'm pretty sure I'm doing it wrong. What i did was i went into repeat battle, exited to lobby with background battling, and then had the UI visible. 

You did it right. Just have the background battling window open and after x amount of runs it should refresh your battles again. You can test it with your pet repeating after 1 battle. It's meant to be a pure afk thing as long as you have inventory space to just set in the background for an extended period of time.
