### ISSUE TITLE
Issue with auto shop screen

### ISSUE THREAD

**Issue by jcurt** [purpxd/E7AutoShop#15]
[error.log](https://github.com/purpxd/E7AutoShop/files/14988438/error.log)
![AutoShopScreen](https://github.com/purpxd/E7AutoShop/assets/10948835/b1aa3fde-0e8a-49e1-a713-0e0477d893c3)

Hello Purpxd,

I was using V1.3 of the AutoShop until today when it stopped working. I installed V1.4, it loads but I get this screen for the Auto Shop. I currently have it installed in C:\E7AutoShop although originally I had it installed on my desktop. Any suggestions?

**Comment by jcurt** [comment]
I’ve also attempted resizing my resolution on the monitor and my resolution in Bluestacks is 1920x1080.

**Comment by purpxd** [comment]
> [error.log](https://github.com/purpxd/E7AutoShop/files/14988438/error.log)
> 
> ![AutoShopScreen](https://github.com/purpxd/E7AutoShop/assets/10948835/b1aa3fde-0e8a-49e1-a713-0e0477d893c3)
> 
> 
> 
> Hello Purpxd,
> 
> 
> 
> I was using V1.3 of the AutoShop until today when it stopped working. I installed V1.4, it loads but I get this screen for the Auto Shop. I currently have it installed in C:\E7AutoShop although originally I had it installed on my desktop. Any suggestions?
> 
> 
> 
> 

Hey jcurt,

I'll have to do an update. It seems like an external resource I was using to pull epic seven event information has stopped working so I'll have to adjust it. Check back in a couple days

**Comment by TrickyVicky4** [comment]
+1 Appreciate your service.

**Comment by purpxd** [comment]
Updated

**Comment by jcurt** [comment]
Thanks for your work on this, confirmed it's working now
