### ISSUE TITLE
windows defender keeps blocking the latest version

### ISSUE THREAD

**Issue by meowmeow01** [purpxd/E7AutoShop#16]
Been using this for more than a year until it stopped working recently, downloaded the latest version and windows defender detects it as a threat.  Never had this issue with older versions before , maybe something needs to looked at?  
(Thanks for the tool btw, saved alot of time.)

![2024-04-20 19_28_59](https://github.com/purpxd/E7AutoShop/assets/141369333/098cde35-e3ea-4af9-851e-4854a9d1f176)

**Comment by purpxd** [comment]
> Been using this for more than a year until it stopped working recently, downloaded the latest version and windows defender detects it as a threat. Never had this issue with older versions before , maybe something needs to looked at? (Thanks for the tool btw, saved alot of time.)
> 
> ![2024-04-20 19_28_59](https://private-user-images.githubusercontent.com/141369333/324219570-098cde35-e3ea-4af9-851e-4854a9d1f176.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2Njc2NDQsIm5iZiI6MTcxMzY2NzM0NCwicGF0aCI6Ii8xNDEzNjkzMzMvMzI0MjE5NTcwLTA5OGNkZTM1LWUzZWEtNGFmOS04NTFlLTQ4NTRhOWQxZjE3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQwMjQyMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmUyNWYzNTgzYWIwMTBmZDFjY2VlZTYzMmQ5MjE0MjE4MDY0N2I5ZDk3MzQ5NWViYzZhNzNmYWZlNTZmNzI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.k7wl6yvvPkf5Z5fcyWnJsWim2AEmx5E43fQnwtqPjWU)

Hey, 
yeah I'm using a new installer method which makes it easier to set up. Disable the real time threat detection during installation and you should be good to go. If any issues arise when running autoshop after installation just whitelist it with defender

**Comment by meowmeow01** [comment]
Installed, Autoshop crashes right away when I click on "start", but Watch e7 Ads is working.

**Comment by purpxd** [comment]
> Installed, Autoshop crashes right away when I click on "start", but Watch e7 Ads is working.

send me what it says in the error.log file

**Comment by purpxd** [comment]
@meowmeow01 I figured it out. Just press light mode or dark mode one time and it will continue to work moving forward.
