### ISSUE TITLE
Autoshop not starting due to WinError 10051

### ISSUE THREAD

**Issue by complexCodeDemon** [purpxd/E7AutoShop#17]
Hello,

I've installed the 2.0 version after following the other issue. My autoshop fails to start up due to a network error. I'm using Python version 3.9.7. This is the command line output after looking up the python version.

python
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

I've tried disabling windows defender (both virus protection and firewall) and it doesn't seem to help.

Below is the error log:

ERROR:root:HTTPSConnectionPool(host='ident.me', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002484F87FBD0>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network'))
Traceback (most recent call last):
  File "urllib3\connection.py", line 198, in _new_conn
  File "urllib3\util\connection.py", line 85, in create_connection
  File "urllib3\util\connection.py", line 73, in create_connection
OSError: [WinError 10051] A socket operation was attempted to an unreachable network

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 793, in urlopen
  File "urllib3\connectionpool.py", line 491, in _make_request
  File "urllib3\connectionpool.py", line 467, in _make_request
  File "urllib3\connectionpool.py", line 1099, in _validate_conn
  File "urllib3\connection.py", line 616, in connect
  File "urllib3\connection.py", line 213, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002484F87FBD0>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 847, in urlopen
  File "urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ident.me', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002484F87FBD0>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "autoshop.py", line 478, in <module>
  File "autoshop.py", line 97, in __init__
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ident.me', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002484F87FBD0>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network'))

**Comment by purpxd** [comment]
> Hello,
> 
> I've installed the 2.0 version after following the other issue. My autoshop fails to start up due to a network error. I'm using Python version 3.9.7. This is the command line output after looking up the python version.
> 
> python Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32 Type "help", "copyright", "credits" or "license" for more information.
> 
> I've tried disabling windows defender (both virus protection and firewall) and it doesn't seem to help.
> 
> Below is the error log:
> 
> ERROR:root:HTTPSConnectionPool(host='ident.me', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002484F87FBD0>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network')) Traceback (most recent call last): File "urllib3\connection.py", line 198, in _new_conn File "urllib3\util\connection.py", line 85, in create_connection File "urllib3\util\connection.py", line 73, in create_connection OSError: [WinError 10051] A socket operation was attempted to an unreachable network
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "urllib3\connectionpool.py", line 793, in urlopen File "urllib3\connectionpool.py", line 491, in _make_request File "urllib3\connectionpool.py", line 467, in _make_request File "urllib3\connectionpool.py", line 1099, in _validate_conn File "urllib3\connection.py", line 616, in connect File "urllib3\connection.py", line 213, in _new_conn urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002484F87FBD0>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "requests\adapters.py", line 486, in send File "urllib3\connectionpool.py", line 847, in urlopen File "urllib3\util\retry.py", line 515, in increment urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ident.me', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002484F87FBD0>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "autoshop.py", line 478, in File "autoshop.py", line 97, in **init** File "requests\api.py", line 73, in get File "requests\api.py", line 59, in request File "requests\sessions.py", line 589, in request File "requests\sessions.py", line 703, in send File "requests\adapters.py", line 519, in send requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ident.me', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002484F87FBD0>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network'))

Working on this right now I'll upload a new installer in a few minutes

**Comment by purpxd** [comment]
Updated

**Comment by complexCodeDemon** [comment]
Thanks for addressing this so quickly. Works like a charm now with the updated installer!
