### ISSUE TITLE
Clicking wrong position

### ISSUE THREAD

**Issue by sethKangg** [purpxd/E7AutoShop#18]
Im using BlueStacks newest version
Have settings for everything 
ADB : On
resolution: 1920x1080
DPI: 240
But still clicking at the bottom

**Comment by purpxd** [comment]
> Im using BlueStacks newest version
> 
> Have settings for everything 
> 
> ADB : On
> 
> resolution: 1920x1080
> 
> DPI: 240
> 
> But still clicking at the bottom

You restarted the emulator? 
Is there anything in the error file?
Can you record a small snippet?

**Comment by sethKangg** [comment]
> You restarted the emulator?
Yeah i have restared 
> Is there anything in the error file? 
Error file empty but 
it return multiple Error green text at result 
like this: (paint version)
![ảnh](https://github.com/purpxd/E7AutoShop/assets/91963611/5e23250e-ada6-4c8a-8df5-333ba34eb18e)

>Can you record a small snippet?
Maybe later cuz im not on computer right now

**Comment by purpxd** [comment]
> > You restarted the emulator?
> > Yeah i have restared
> > Is there anything in the error file?
> > Error file empty but
> > it return multiple Error green text at result
> > like this: (paint version)
> > ![ảnh](https://private-user-images.githubusercontent.com/91963611/331753954-5e23250e-ada6-4c8a-8df5-333ba34eb18e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMDYyNjIsIm5iZiI6MTcxNjAwNTk2MiwicGF0aCI6Ii85MTk2MzYxMS8zMzE3NTM5NTQtNWUyMzI1MGUtYWRhNi00YzhhLThkZjUtMzMzYmEzNGViMThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDA0MTkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMGE1YzA2YTgyMDE5ZjcyYTNkNTA0ZTk3YTNiMzk5Y2I1NTAxZGMzMDQ3MGQ0YWZkNzk4ZGI0NGVjM2ZjY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t-gHLyAAO4SOsjDzDH806tYEF-WqHgOJCmsTo-h6-BA)
> 
> > Can you record a small snippet?
> > Maybe later cuz im not on computer right now

This is the type of error where the display isn't seen as 1920 x 1080. I can't replicate the issue on my end so it's hard to troubleshoot. Others have found success using a different emulator or re-creating a new instance.

**Comment by sethKangg** [comment]
> This is the type of error where the display isn't seen as 1920 x 1080. I can't replicate the issue on my end so it's hard to troubleshoot. Others have found success using a different emulator or re-creating a new instance.

here is the vid link for the above: https://streamable.com/1qpfhg

i will try create new instance and check if it's possible

**Comment by iamAika** [comment]
im having the same problem, i think i updated the instance version of muy bluestacks to pie 64bit, maybe that has some efect on the bot? i also play league of legends and vanguard update came last week i think, maybe that?

**Comment by purpxd** [comment]
> im having the same problem, i think i updated the instance version of muy bluestacks to pie 64bit, maybe that has some efect on the bot? i also play league of legends and vanguard update came last week i think, maybe that?

I also use pie-64 and have no issues. Vanguard shouldn't have any effect on the program at all. 

![image](https://github.com/purpxd/E7AutoShop/assets/136267320/d38b071a-7ada-45b4-9a1e-6452b73464da)
![image](https://github.com/purpxd/E7AutoShop/assets/136267320/cf065831-86b2-47e6-8fb3-f6143480a7ec)

With these same exact settings, If you guys are still experiencing the same issue then I would have to recommend a different emulator (LD player). The only thing I could tell is our pie version is different, I'm not sure how that would affect anything. But hopefully a new emulator or a bluestacks version change would resolve this issue

**Comment by sethKangg** [comment]
well LDPlayer works fine so i close it ZZZ.
nice project btw very fast
