### ISSUE TITLE
Crashes within 1-2 minutes of being open

### ISSUE THREAD

**Issue by blakethrowawayes3** [purpxd/E7AutoShop#19]
It was an error reported in the past: error folder shows this:
ERROR:root:cannot identify image file <_io.BytesIO object at 0x0000029D64B5A5C0>
Traceback (most recent call last):
  File "scripts\shop.py", line 239, in main
    screenshot = self.screen()
                 ^^^^^^^^^^^^^
  File "scripts\shop.py", line 115, in screen
    screenshot = Image.open(BytesIO(img_bytes))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PIL\Image.py", line 3339, in open
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x0000029D64B5A5C0>

I'm on the right reso, adb enabled, tried it in with admin enabled, and tried it in several locations on a few different drives.

**Comment by MellowRushGG** [comment]
I am also having this issue and did everything mentioned here at the end :/ What solved this?

Also, thank you purp for making this tool :)
