### ISSUE TITLE
Autorefresh is selecting fodder then getting stuck on fodder purchase screen.

### ISSUE THREAD

**Issue by BiggusBrain** [purpxd/E7AutoShop#20]
I've noticed that when the bookmark is last on the list and there is a fodder above it sometimes the automatic clicking will select the fodder and then be stuck clicking randomly on the purchase screen while being perpetually stuck.

This has happened twice now, I'm unsure if this happens 100% a bookmark is last on list with a fodder directly above it or if there is some sort of % chance of it occurring with those 2 conditions being met. 

The 2nd time this happened I clicked off the mob purchase screen so I wouldn't have to reset the autoshop but it immediately re-selected the fodder for purchase and got stuck again clicking everywhere.

![Example 1](https://github.com/purpxd/E7AutoShop/assets/173642687/7df7ddf9-0d6c-4516-afd1-25d88f229af0)

**Comment by purpxd** [comment]
> I've noticed that when the bookmark is last on the list and there is a fodder above it sometimes the automatic clicking will select the fodder and then be stuck clicking randomly on the purchase screen while being perpetually stuck.
> 
> This has happened twice now, I'm unsure if this happens 100% a bookmark is last on list with a fodder directly above it or if there is some sort of % chance of it occurring with those 2 conditions being met.
> 
> The 2nd time this happened I clicked off the mob purchase screen so I wouldn't have to reset the autoshop but it immediately re-selected the fodder for purchase and got stuck again clicking everywhere.
> 
> ![Example 1](https://private-user-images.githubusercontent.com/173642687/342170382-7df7ddf9-0d6c-4516-afd1-25d88f229af0.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyOTY1NTQsIm5iZiI6MTcxOTI5NjI1NCwicGF0aCI6Ii8xNzM2NDI2ODcvMzQyMTcwMzgyLTdkZjdkZGY5LTBkNmMtNDUxNi1hZmQxLTI1ZDg4ZjIyOWFmMC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQwNjE3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjM2ZTlhOGRiNTNhMzM0ZTYxNjEwODZkYTlhNmI3ZDdkMjQyMTVhYjk0OTVlYjk5YTQ4NzEwMDljZjQyYThjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BNLsnhE8Y0x4vQHgTvD4XH_Jj-QjawnETQxdk0ldhp4)

Thanks for reporting this issue and supplying specific details. I've updated the app and you can download the new version.
