### ISSUE TITLE
Errors via Dispatch Missions

### ISSUE THREAD

**Issue by pleasefixomg** [purpxd/E7AutoShop#24]
Dispatch missions cause the app to error out and skip whatever was on that page without purchasing anything.

While the app does re-start the dispatch mission properly, if there were covenant or mystic bookmarks on the page at the time a dispatch mission ended, they would not be purchased and skipped.

I had one where covenant were on slot 2 of 6. That refresh reads:

Level 55 equip grade good
Error <-the covenants
Fodder
Friendship Bookmarks
Error
Error

Here, I assume, the first screenshot was taken nearly simultaneously with the dispatch popup. The dispatch was then restarted, the second screenshot for the bottom two items on the page was skipped, and the app began another refresh skipping the covenants.

It seems default behaviour of the app on a new set of refreshes or after an error is to refresh the page first and then start taking screenshots. Maybe changing the app to scan the current page first before refreshing anything would alleviate this.

**Comment by purpxd** [comment]
> Dispatch missions cause the app to error out and skip whatever was on that page without purchasing anything.
> 
> 
> 
> While the app does re-start the dispatch mission properly, if there were covenant or mystic bookmarks on the page at the time a dispatch mission ended, they would not be purchased and skipped.
> 
> 
> 
> I had one where covenant were on slot 2 of 6. That refresh reads:
> 
> 
> 
> Level 55 equip grade good
> 
> Error <-the covenants
> 
> Fodder
> 
> Friendship Bookmarks
> 
> Error
> 
> Error
> 
> 
> 
> Here, I assume, the first screenshot was taken nearly simultaneously with the dispatch popup. The dispatch was then restarted, the second screenshot for the bottom two items on the page was skipped, and the app began another refresh skipping the covenants.
> 
> 
> 
> It seems default behaviour of the app on a new set of refreshes or after an error is to refresh the page first and then start taking screenshots. Maybe changing the app to scan the current page first before refreshing anything would alleviate this.

Thanks for pointing this out. I didn't think of it, but this could be the reason users experience an error after a few hundred refreshes.

Since the dispatch mission pop up is so unpredictable. I just added a quick series of clicks with the hopes it'll close the window before a screenshot is taken. It seems like the mission pops up after the clicks, which is a very slim window. Honestly the best solution is to either not do any dispatches during your shop refreshes or time your refreshing within your dispatch timer. It's about 50mins/1k ss. The chances of your situation happening is slim.

**Comment by pleasefixomg** [comment]
> Honestly the best solution is to either not do any dispatches during your shop refreshes or time your refreshing within your dispatch timer. It's about 50mins/1k ss. The chances of your situation happening is slim.

Yeah I already started doing this. I know having bookmarks come up during this is a very small chance of occurrence. Just bringing it up anyway. And it seems doing so maybe shed light on something else so mission accomplished lol.
