### ISSUE TITLE
Does it support Chinese server?

### ISSUE THREAD

**Issue by Leoawwman** [purpxd/E7AutoShop#3]
Hello! I want to know if it supports chinese server? if not, how can i modify it. thanks!

**Comment by purpxd** [comment]
> Hello! I want to know if it supports chinese server? if not, how can i modify it. thanks!

Hello,

Yes it should work with the Chinese servers as well

**Comment by Leoawwman** [comment]
已收到  谢谢!

**Comment by purpxd** [comment]
> 已收到 谢谢!

不客气！

**Comment by Leoawwman** [comment]
thanks bro,i'll try it later

**Comment by Leoawwman** [comment]
After i Launch the AutoShop program 
it shows：
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

**Comment by purpxd** [comment]
> 

did you follow the installation steps on version 1.3?

**Comment by Leoawwman** [comment]
yes, step by step, it was all ok until step5

**Comment by Leoawwman** [comment]
![image](https://github.com/purpxd/E7AutoShop/assets/57946374/ddc21f62-118e-4bb7-b07f-b2a52b977dbc)

**Comment by natedogg69** [comment]
What it's that

**Comment by Leoawwman** [comment]
已收到  谢谢!

**Comment by purpxd** [comment]
> 已收到 谢谢!

Hi Leo, 

did you manage to get it working?

**Comment by Leoawwman** [comment]
已收到  谢谢!
