### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by meowmeow01** [purpxd/E7AutoShop#4]
The last time I used it was about two weeks ago and it's been working fine without any issue.  Today it started to close itself down when I start the refresh.

I've tried reinstalling it, BS 5, resolution 1920x1080, ADB enabled.

No idea where the issue is coming from so I'm just wondering if you can give me an idea from the error log below, thanks.

Error log showing:
ERROR:root:cannot identify image file <_io.BytesIO object at 0x0000020398C5DCB0>
Traceback (most recent call last):
  File "C:\Users\X\Desktop\E7 Autoshop\E7AutoShop\build\shop.py", line 263, in main
    screenshot = self.screen()
  File "C:\Users\X\Desktop\E7 Autoshop\E7AutoShop\build\shop.py", line 134, in screen
    screenshot = Image.open(BytesIO(img_bytes))
  File "C:\Users\X\Desktop\E7 Autoshop\E7AutoShop\virtual_env\lib\site-packages\PIL\Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)

**Comment by purpxd** [comment]
> 
Try opening your task manager and in your processes tab, look to see if adb.exe is running. If it is then end the process and restart the app. Alongside that also completely exit out of your emulator as well and relaunch.

**Comment by meowmeow01** [comment]
Thanks for the response, I did the steps you mentioned above but no luck...  Installed LDplayer and it worked right away, not sure what is the issue with BS but I'll just stick with LD for now.  Thanks!

**Comment by purpxd** [comment]
> 

That's great I'm glad you were able to get it working. I'll to try to replicate that problem with Bluestacks 5 and hopefully come up with a solution in the future.
