### ISSUE TITLE
ERROR:root:cannot identify image file

### ISSUE THREAD

**Issue by reihikari** [purpxd/E7AutoShop#5]
ERROR:root:cannot identify image file <_io.BytesIO object at 0x0000015DB186A700>
Traceback (most recent call last):
  File "C:\Users\reihi\Downloads\E7AutoShop\build\shop.py", line 263, in main
    screenshot = self.screen()
  File "C:\Users\reihi\Downloads\E7AutoShop\build\shop.py", line 134, in screen
    screenshot = Image.open(BytesIO(img_bytes))
  File "C:\Users\reihi\Downloads\E7AutoShop\virtual_env\lib\site-packages\PIL\Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x0000015DB186A700>

Is this mean I need to take my own picture for this if I may ask?

**Comment by purpxd** [comment]
Hello,
No do you not need to take your own screenshots.
Was there any issues during your installation?

**Comment by reihikari** [comment]
I don't think so, everything goes smoothly but when I launch the program it just crashes and gives me an error file like above. Oh and this is after I enter the number of SS that I want to refresh so at least the program is up.

**Comment by purpxd** [comment]
You did enable adb in the advanced settings within the emulator right?

**Comment by reihikari** [comment]
Yes I am, but I think at 1 point it said the adb version(36) doesnt match this client(41).

**Comment by purpxd** [comment]
Please visit this link: https://developer.android.com/tools/releases/platform-tools#downloads

Follow these steps:

1. Download the platform tools then extract it in your downloads folder.
2. Copy three files from the platform-tools folder into C:\Users\reihi\Downloads\E7AutoShop\adb folder (adb, AdbWinApi.dll, AdbWinUsbApi.dll)
3. Within your task manager end any processes called adb
4. Relaunch the Autoshop program and try to start a run

**Comment by reihikari** [comment]
Tks you so much I will try it later.

**Comment by purpxd** [comment]
You're welcome. Let me know if it works for you later.

**Comment by reihikari** [comment]
I just tried again and the error log showed the same error. I punched in the SS number, press run and the app crashed.

**Comment by purpxd** [comment]
Can you check if adb.exe is even running in the task manager?

**Comment by reihikari** [comment]
Yes it is, I also tried close it and restart the app and error log showed the same

**Comment by purpxd** [comment]
What emulator are you using?

**Comment by reihikari** [comment]
It's Bluestack 5, I just reinstalled it. Maybe due to hyper V requirement so it not boost up properly as I tried to bypass it with run as admin

**Comment by purpxd** [comment]
I see. I am also using Bluestacks 5 and runs with no issues. Since you updated the adb version to match with Bluestacks version it should be working. If you still can't run it after reinstalling bluestacks then I would kill all adb processes. 

You can do so by going into task manager > Performance tab > Open resource monitor > CPU tab 

Find all adb.exe, right click and end process tree for all. Restart Bluestacks then try again. Hopefully this works

**Comment by reihikari** [comment]
Tks brother it works now, reinstall BS5 and I need to use Nox to active hyper V cause BS5 didn't.

**Comment by purpxd** [comment]
> Tks brother it works now, reinstall BS5 and I need to use Nox to active hyper V cause BS5 didn't.

That's great! I'm glad it worked. Stay tuned for future update soon as well. I got pure auto hunt and auto expeditions cookin up!
