### ISSUE TITLE
Error for just the first item

### ISSUE THREAD

**Issue by complexCodeDemon** [purpxd/E7AutoShop#8]
Hello,

I've been using the program for a while and just noticed this error a few days ago. The script does not seem to recognize the first item in my shop list. I've tried going through the entire setup process again, and even reinstalled bluestacks.

If bookmarks show up in item 1, the script just scrolls right past it.

![python_VxQSHxHznr](https://github.com/purpxd/E7AutoShop/assets/154905439/6dd99c01-e894-411d-b790-7a8b7c065807)

**Comment by purpxd** [comment]
> Hello,
> 
> I've been using the program for a while and just noticed this error a few days ago. The script does not seem to recognize the first item in my shop list. I've tried going through the entire setup process again, and even reinstalled bluestacks.
> 
> If bookmarks show up in item 1, the script just scrolls right past it.
> 
> ![python_VxQSHxHznr](https://private-user-images.githubusercontent.com/154905439/292886269-6dd99c01-e894-411d-b790-7a8b7c065807.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NjYzNjMsIm5iZiI6MTcwMzY2NjA2MywicGF0aCI6Ii8xNTQ5MDU0MzkvMjkyODg2MjY5LTZkZDk5YzAxLWU4OTQtNDExZC1iNzkwLTdhOGI3YzA2NTgwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QwODM0MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTM3NTUwMGI3NjUxNWY0ZWZlMDdhYzE1ODcyM2I3ZWVhOTdiMjdjZjRjMDhlNzIyOTQ0MzdiYzg5OGI4NmE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w5wv9_nUhpdJlaLmzPZn-H6P8ITZwWANnGRquHCfvcQ)

Hi there,
Thanks for using the program and reporting this issue. I was able to replicate the problem. For now as I do some changes to the code. Please adjust your in-game background to something a little darker. For some reason the current xmas theme (probably because of it's brightness) is affecting the first row of the shop. I hope this helps! Thanks

**Comment by complexCodeDemon** [comment]
Hello,

Thanks for looking into the issue and getting back so quickly! I changed the lobby background as you suggested and it fixed the issue right away!

**Comment by purpxd** [comment]
You're welcome. Glad it fixed the problem!

Happy Holidays!
