### ISSUE TITLE
not buying covenant on 1st slot

### ISSUE THREAD

**Issue by Fazzo** [purpxd/E7AutoShop#9]
I saw it happen 2 times, one with 5x covenant bookmarks and another time with 50x mystic medals, if they are placed on the first slot of the shop it just skips it and refreshes to the next page. Any chance to check this?

**Comment by purpxd** [comment]
> I saw it happen 2 times, one with 5x covenant bookmarks and another time with 50x mystic medals, if they are placed on the first slot of the shop it just skips it and refreshes to the next page. Any chance to check this?

Hi,
this is an issue I've recently became aware of. You can fix it by changing the lobby background to a darker theme. The xmas theme is interfering with the shop. I hope it helps!
